### PR TITLE
Make watcher ignore irrelevant files

### PR DESCRIPTION
**Pull request by lionel-rowe**
Whitelist only relevant files to watch.

**Matches:**

```
about.json

assets/font.woff2
assets/background.jpg
assets/icon.svg

common/common.scss
common/head_tag.html
common/header.html
common/after_header.html
common/body_tag.html
common/footer.html
common/embedded.scss

desktop/desktop.scss
desktop/head_tag.html
desktop/header.html
desktop/after_header.html
desktop/body_tag.html
desktop/footer.html

mobile/mobile.scss
mobile/head_tag.html
mobile/header.html
mobile/after_header.html
mobile/body_tag.html
mobile/footer.html

settings.yml

locales/en.yml
locales/zh_CN.yml
```

**Doesn't match:**

```
src/thing.js
scripts/script.js
package.json
.gitignore
test/thing.test.js
LICENSE
README.md
```

### CODE REVIEW

**Comment by SamSaffron** [comment]
I am kind of mixed on this cause we plan to add support very shortly for JS splitting. 

@davidtaylorhq  are you ok to merge this in the interim and update once you get js splitting?

**Comment by lionel-rowe** [comment]
Code splitting would be awesome. Depending on directory structure, you could just match for `common\/.+\.(?:html?|js|s?css)` etc. instead of individual files.

Another alternative would be blacklisting instead of whitelisting, reading from a `.discoursethemeignore` file, but that seems a bit fiddly IMO.

**Comment by davidtaylorhq** [comment]
I think we could add a whitelist for the top-level of files/folders. Any files inside a whitelisted folder would then be included, so there wouldn't be any issues with JS/CSS splitting.

@lionel-rowe what's the motivation here? The server should ignore any files that it doesn't understand.

**Comment by lionel-rowe** [comment]
>@lionel-rowe what's the motivation here? The server should ignore any files that it doesn't understand.

Mainly just to reduce unnecessary uploads. I was finding, using nodemon and webpack, that I'd have to wait for the source files to upload first, followed by the relevant files. Once code splitting is enabled, I probably won't bother with nodemon and webpack any more, though I guess someone compiling from TypeScript, using experimental features with Babel, etc. would still have that problem.

There are also other irrelevant files that live in the parent directory — tests, `.gitignore`, and so on.

**Comment by davidtaylorhq** [comment]
:+1: I think having a **top level** whitelist would be ok. Then it's easy for us to add directories in future. 

It looks like this PR is controlling what changes **trigger** an upload. To control what is actually uploaded you will need to update this bit: https://github.com/discourse/discourse_theme/blob/f7b6e2e2337d165ddd5dc2d52511f1778f254340/lib/discourse_theme/uploader.rb#L18-L19

Incidentally, it looks like we already skip the `src` directory and any dotfiles.

**Comment by lionel-rowe** [comment]
Good point. Actually, that's interesting about `src`, I think it may be because I was using a `bundles` directory as an intermediate build step. I'll see if moving everything into `src` and its subdirectories solves the problem.

**Comment by lionel-rowe** [comment]
@davidtaylorhq I think what's happening is that the watcher triggers a new tar file to be generated and uploaded each time, even if none of the relevant files have actually changed. Without the extra filter on the watcher, it's still triggering an upload every time a file changes, even for dotfiles or files in `src`.

To keep the watcher consistent with the uploader, it'd probably make the most sense to simply blacklist `src` and dotfiles. I'll update this PR accordingly. @SamSaffron perhaps you could put a note in the meta topic about keeping any files that shouldn't be uploaded inside `src`?

**Comment by SamSaffron** [comment]
I think that post is a wiki on meta feel totally free to add a note. 

David will get this PR sorted, I think we are simply waiting a bit cause CSS / JS splitting is something we will be working on next week so it makes sense to just update the theme cli when we release the new feature.

**Comment by SamSaffron** [comment]
CSS and JS splitting is done now.  I am closing this for now, @davidtaylorhq  feel free to follow this up if you think it makes sense.

**Pull request closed without merging**
